BugBusterSWE/MaaS

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

*Numero del Task/Issue correlato/a*: #29
Aggiunto template per issue e pull requests

Issue#29 - Add issue template

---

Procfile
app.json
package.json

*Numero del Task/Issue correlato/a*: #41 
- Scritto Procfile per heroku, che ora è capace di fare il deploy. Attualmente un deploy di testing è disponibile a questo indirizzo: https://testmaaswe.herokuapp.com/. Questo container si aggiornerà a ogni push su master, dopo che la build dei sistemi CI daranno l'ok.
- Scritto app.json, che però è solamente testabile nel master. App.json permetterà di fare dei deploy su heroku temporanei solamente per le pull request. In questo modo sarà possibile vedere, oltre i controlli di travis e jenkins, se il deploy su heroku si effettua con successo.

Issue#41 - Scritto Procfile

---

README.md
app.json

*Numero del Task/Issue correlato/a*: #43 
Fix di un typo per provare che funzioni l'auto deploy di una macchina su Heroku.

Issue #43 - Minor fix

---

src/public/src/scripts/react/components/administrator/addCompany.tsx
src/public/src/scripts/react/components/administrator/addMemberToCompany.tsx
src/public/src/scripts/react/components/administrator/inviteSuperAdmin.tsx
src/public/src/scripts/react/components/administrator/showCompanies.tsx
src/public/src/scripts/react/components/administrator/showCompanyMembers.tsx
src/public/src/scripts/react/components/errorMessageComponent.tsx
src/public/src/scripts/react/components/home.tsx
src/public/src/scripts/react/components/login.tsx
src/public/src/scripts/react/components/recoveryPassword.tsx
src/public/src/scripts/stores/sessionStore.ts

*Numero del Task/Issue correlato/a*: #57
Ho aggiunto <messageError error="..." /> all'html delle form e ho cambiato di posizione /* tslint:disable: max-line-length */

Issue#57 - Add messageError component and change tslin:disable position

---

src/main.ts

*Numero del Task/Issue correlato/a*: #51
Rimossa la funzione main nel file `main.ts` che risultava nella documentazione

Issue#51 - Rimossa funzione main dalla documentazione

---

src/apidoc.json
src/routes/companyRouter.ts
src/routes/databaseRouter.ts
src/routes/dslRouter.ts
src/routes/userRouter.ts

*Numero del Task/Issue correlato/a*: #47
Sostituito `/api/...` in `api/...`.

Issue#47 - Correct all URL

---

test/config/indexTest.ts

*Numero del Task/Issue correlato/a*: #78 
Scritto un test per verificare che il tutto funzioni. Questo sara' utile perche' in futuro permettera' a chi scrivera' i test di connettersi a un altro database senza intaccare quello di produzione.

Issue#78 - Add a test for custom database parameters

---

src/maas.ts

*Numero del Task/Issue correlato/a*: #87
Riscritto MaaS.ts come una classe. Questo e' utile perche' permettera' di eseguire test su database custom.

Issue#87 - Create MaaS.ts as a class

---

src/routes/companyRouter.ts

*Numero del Task/Issue correlato/a*: #90 
*Breve descrizione della soluzione adottata*: Cancellati campi segnalati nella issue

Issue #90 - Fixed fields on create company response

---

src/routes/companyRouter.ts

*Numero del Task/Issue correlato/a*: #96 
*Breve descrizione della soluzione adottata*: Aggiunto status

Issue#96 - Aggiunto status errore alla route createCompany

---

package.json

*Numero del Task/Issue correlato/a*: #109 
Fissata la versione di Typedoc alla 0.3.12

Fixed version of Typedoc to the 0.3.12

---

src/models/databaseModel.ts

*Numero del Task/Issue correlato/a*: #128 
*Breve descrizione della soluzione adottata*: aggiunto export mancante necessario per eseguire i test

Issue#128 Update databaseModel.ts for tests 

---

src/lib/authenticationChecker.ts

*Numero del Task/Issue correlato/a*: #123
*Breve descrizione della soluzione adottata*: Fixato bug sull'accesso ai metodi statici privati della classe

issue#123 - Fixed bug on authentication checker

---

src/public/src/scripts/actions/userActionCreator.ts
src/public/src/scripts/react/components/administrator/superAdminManagement.tsx
src/public/src/scripts/stores/userStore.ts
src/public/src/scripts/utils/userAPIs.ts

*Numero del Task/Issue correlato/a*: #108 
Creata pagina, API e action per l'aggiunta di un nuovo super admin.
Unico difetto che non riesco a risolvere: quando capita un errore compare il badge rosso che sengala l'errore. Se si cambia pagina e si ritorna per aggiungere un nuovo super admin rimane il badge di errore precedente.
Chiedo suggertimenti su questa cosa a @drigoni e/o @EmanueleC! :blush: 
P.S.: Sono cosciente che la PR va da una issue a un'altra issue. Sono accordato con @drigoni per ridurre il numero di conflitti :blush:.

Issue#108 - Add a new Super Admin

---

src/models/userModel.ts
src/routes/userRouter.ts

*Numero del Task/Issue correlato/a*: #130 
Scritta API per ottenere i SuperAdmin presenti in MaaS. @WeissL sarà necessario scrivere la relativa documentazione nella ST, perchè non esiste proprio.

Issue#130 - Write API for get all SUPERADMINs

---

src/routes/userRouter.ts

*Numero del Task/Issue correlato/a*: #137 
Riscritta e-mail di registrazione in inglese.

Issue#137 - Translate e-mail registration in English

---

src/models/userModel.ts
src/public/src/scripts/actions/sessionActionCreator.ts
src/routes/userRouter.ts

*Numero del Task/Issue correlato/a*: #155
*Breve descrizione della soluzione adottata*: Fix password change method

Issue#155 - Fix Password

---

src/public/src/scripts/actions/userActionCreator.ts
src/public/src/scripts/react/pages/common/updateProfilePassword.tsx
src/public/src/scripts/utils/userAPIs.ts

*Numero del Task/Issue correlato/a*: #149
Sistemato la pagina per cambiare la password

Issue#149 - Fix change password

---

src/public/src/scripts/actions/userActionCreator.ts
src/public/src/scripts/main.tsx
src/public/src/scripts/react/components/navbar/navbarAdmin.tsx
src/public/src/scripts/react/pages/owneradmin/addMember.tsx
src/public/src/scripts/react/pages/owneradmin/editMember.tsx
src/public/src/scripts/react/pages/owneradmin/showMemberList.tsx
src/public/src/scripts/stores/companyStore.ts
src/public/src/scripts/stores/userStore.ts
src/public/src/scripts/utils/companyAPIs.ts
src/public/src/scripts/utils/userAPIs.ts

*Numero del Task/Issue correlato/a*: #136 
Aggiunta sezione riguardo alla gestione dei membri di una company.
Un *OWNER* ora puo':
- Vedere una lista dei membri della sua company
- Modificare il livello di accesso ai membri della company
- Eliminare membri dalla company
- Aggiungere membri dalla company
Cosa manda da fare:
N.B.: e' possibile provare il funzionamento in dpolonio.herokuapp.com

Issue#136 - Admin/Owner member management

---

src/public/src/scripts/stores/sessionStore.ts

*Numero del Task/Issue correlato/a*: #160 
La sessione ora usa sessionStorage per mantenere i dati all'interno della scheda

Issue#160 - Fix login

---

src/lib/authenticationChecker.ts
src/lib/levelChecker.ts
test/lib/authenticationCheckerTest.ts
test/lib/dslCheckerTest.ts
test/lib/levelCheckerTest.ts

*Numero del Task/Issue correlato/a*: #112
*Breve descrizione della soluzione adottata*: scritti test di unità per i checker del backend

Issue#112- Write unit tests for backend checkers

---

package.json
src/routes/companyRouter.ts
src/routes/databaseRouter.ts
src/routes/dslRouter.ts
src/routes/userRouter.ts
typedoc.json

Sistemata la documentazione visto che non compilava

Add RAchanges
